travis:
  secure:
    BINSTAR_TOKEN: SJgPChTy6DQmr+vA0CKB+xSV22QqMTuGH+CVzenV13zNfzQC7MgyyD6byYE66Twp4dYZBk7SmPsx9rvL6kX4di+J4cBCgweGhlvzX8FjOiatCJ8uVHRkXY8LO4TFB9DqtoUBIiUDW9bBZ5K2d+0OluD/dVj1NAOzkXXEtMiJAgfitQunY6d/pyP8lpbjQdDfS1mFmDV4i4jhmMehKI4zQhkbYxMsnOAkD9BIfQ0FOs+jRGaUF3WkwBZxu8BGlG6JKPfObmpI9qV7dEw0DMR9hk2o8VUYfI6A3n2NrVYQ87zM6MYIsW/eJKjYpQvb97HeSWW/Qdl7hSA5xBfvCwZ4quSvcZv0+v6UUIqe+Fc5V9cPFyg1bUBLXRFkqVtblekAi2/gvmUqv8NSsSLEdjo8wpLFxai17tmGE7yLYz8WxftrUrogAzuMh+/lZ/wMHwCV4yZhE/HsdVzMD3YBqvR2zdDFfcXxk3ayuDqk2jOzyIMxTcBiOrp2RLzDQUWG0kwwguYt4fufTIwTfbSGFTfRBlW7qKOUuP5zw8wGPcdVQWj+GQRFAUj26S7ocb/NWbcoMwNCX6+ecTU8mykvy23QvHUaAHPDDKWHcqnx4v918db3Qaep0V4VQ8nnbV9TIc70Tyt0Jg4eKaERgpRGAFkZ9ewrJjDOJfIUj41oobYA45k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
