travis:
  secure:
    BINSTAR_TOKEN: zMldcewRgHW5eIR3spFwV3sihHaE/7rB7RBBbs33wz+822edv88XM/Jzqbu6tf7e6GrJpKZare3fjxCgwXy85HVMgoZhlz5auksXG9B94uHrmRwk/0xH7MysYG2TZIObL3g3/BMkqCOhvgqqEu0fl6cyLCFXg/KtgUmWBptS07vWlU10HfJQ5u9mIRfme7w8caCsL0alYmORXzA9d8Ei2NzlADOh5LooPXgxfQY+RPdQSnNDVSr/+4Yzr7KUbdH65fKTlxRFpUGld22CqOqUgKFos7FKslxaP2J+3pcWQHbB8HxV6KLpQQjMAsuyq8wy27t7cUbebEWjeWsm1MvRLw5Tg16zYSkxfrfI+LFJuHC4pgst8QJ/Kz1mKu2QgMHIrNiZVRATtqTTdfWJjS6Ld+Uq1NyFR5odlBIi/0Gp31UfC37QJzwgf/VTgl7l3uiEX09ZnzN00Rckn+PmicV+MjtEbt4CMQCIkngDaLa+20+5ey1xstTO0m6BOeBBLoUujlMyoxED4u88aSI+9ddlNF2l8CiDHVqczPXrFkA5rAwdiMoeGYWsyNPRkdcPFUHNuWf9ipfIk+No4XYg0xUllVpDCkQTmS2nytLEtW23C1xLBmM+AoW0Qto7QcGR5JBxsGKNyqdkR0ucqm1l2NR7BFh+bi75BwwCueZ2cdUeg9M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
